USE airport_management_system;
-- Dropping and re-adding the STATE column
ALTER TABLE AIRPORT DROP COLUMN STATE;
ALTER TABLE AIRPORT ADD STATE VARCHAR(20);

-- Renaming columns and tables
ALTER TABLE AIRPORT RENAME COLUMN AIRPORT_NAME TO AIR_NAME;
RENAME TABLE AIRPORT TO AIRPORT_DETAILS;
RENAME TABLE AIRPORT_DETAILS TO AIRPORT;
ALTER TABLE AIRPORT RENAME COLUMN AIR_NAME TO AIRPORT_NAME;
