DROP DATABASE IF EXISTS airport_management_system;

CREATE DATABASE airport_management_system;

USE airport_management_system;

-- Ensure the InnoDB engine is used for foreign key support
CREATE TABLE AIRPORT (
    AIRPORT_NAME VARCHAR(20) NOT NULL PRIMARY KEY,
    CITY VARCHAR(20),
    STATE VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE AIRLINE (
    AIRLINE_ID INT NOT NULL PRIMARY KEY,
    AIRLINE_NAME VARCHAR(10),
    AIRPORT_NAME VARCHAR(20),
    FOREIGN KEY (AIRPORT_NAME) REFERENCES AIRPORT(AIRPORT_NAME)
) ENGINE=InnoDB;

CREATE TABLE CONTAINS (
    AIRPORT_NAME VARCHAR(20),
    AIRLINE_ID INT,
    FOREIGN KEY (AIRPORT_NAME) REFERENCES AIRPORT(AIRPORT_NAME),
    FOREIGN KEY (AIRLINE_ID) REFERENCES AIRLINE(AIRLINE_ID)
) ENGINE=InnoDB;

CREATE TABLE FLIGHT (
    FLIGHT_NO INT NOT NULL PRIMARY KEY,
    SOURCE VARCHAR(20) NOT NULL,
    DESTINATION VARCHAR(20) NOT NULL,
    D_TIME DATETIME,
    A_TIME DATETIME,
    DURATION INT NOT NULL,
    AIRLINE_ID INT,
    FOREIGN KEY (AIRLINE_ID) REFERENCES AIRLINE(AIRLINE_ID)
) ENGINE=InnoDB;

CREATE TABLE EMPLOYEE (
    E_ID INT PRIMARY KEY,
    NAME VARCHAR(20),
    ADDRESS VARCHAR(20),
    SEX VARCHAR(10),
    SALARY INT,
    AGE INT,
    AIRPORT_NAME VARCHAR(20),
    FOREIGN KEY (AIRPORT_NAME) REFERENCES AIRPORT(AIRPORT_NAME)
) ENGINE=InnoDB;

CREATE TABLE EMP_PHONE_NO (
    E_ID INT,
    PHONE_NO VARCHAR(11),
    FOREIGN KEY (E_ID) REFERENCES EMPLOYEE(E_ID)
) ENGINE=InnoDB;

CREATE TABLE PASSENGER (
    PASSPORT_NO VARCHAR(20) NOT NULL PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(20),
    SEX VARCHAR(5),
    DOB DATE,
    AGE INT,
    FLIGHT_NO INT,
    TICKET_NO VARCHAR(20),
    FOREIGN KEY (FLIGHT_NO) REFERENCES FLIGHT(FLIGHT_NO)
) ENGINE=InnoDB;

CREATE TABLE SERVES (
    E_ID INT,
    PASSPORT_NO VARCHAR(20),
    FOREIGN KEY (E_ID) REFERENCES EMPLOYEE(E_ID),
    FOREIGN KEY (PASSPORT_NO) REFERENCES PASSENGER(PASSPORT_NO)
) ENGINE=InnoDB;

CREATE TABLE PASSENGER_PHONE_NO (
    PASSPORT_NO VARCHAR(20),
    PHONE_NO VARCHAR(11),
    FOREIGN KEY (PASSPORT_NO) REFERENCES PASSENGER(PASSPORT_NO)
) ENGINE=InnoDB;

CREATE TABLE TICKET (
    TICKET_NO VARCHAR(20) NOT NULL PRIMARY KEY,
    AIRLINE_NAME VARCHAR(20) NOT NULL,
    PRICE INT NOT NULL,
    SEAT_NO VARCHAR(20),
    CLASS VARCHAR(5),
    D_TIME DATETIME,
    A_TIME DATETIME,
    DURATION INT,
    DESTINATION VARCHAR(20),
    SOURCE VARCHAR(20),
    PASSPORT_NO VARCHAR(20),
    PASSENGER_NAME VARCHAR(20),
    FOREIGN KEY (PASSPORT_NO) REFERENCES PASSENGER(PASSPORT_NO)
) ENGINE=InnoDB;

